# Generated by Django 4.0.3 on 2022-04-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
