# Generated by Django 4.0.3 on 2022-04-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_bucket_bucketproduct_bucket_products_bucket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorys',
            field=models.ManyToManyField(related_name='products', to='marketplace.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='marketplace.category'),
        ),
    ]
