# Generated by Django 4.0.3 on 2022-04-12 16:22

from django.db import migrations

def make_many_categorys(apps, schema_editor):
    """
        Adds the Author object in Book.author to the
        many-to-many relationship in Book.authors
    """
    Product = apps.get_model('marketplace', 'Product')

    for product in Product.objects.all():
        product.categorys.add(product.category)

class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_categorys_alter_product_category'),
    ]

    operations = [
        migrations.RunPython(make_many_categorys),
    ]






