# Generated by Django 4.0.3 on 2022-04-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20220412_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='bucketproduct',
            unique_together={('product', 'bucket')},
        ),
    ]
