# Generated by Django 3.2.13 on 2022-04-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
