# Generated by Django 3.2.13 on 2022-04-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_delete_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('announcement_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('was_announced', models.BooleanField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categories', models.ManyToManyField(to='marketplace.Category')),
                ('products', models.ManyToManyField(to='marketplace.Product')),
            ],
        ),
    ]
