# Generated by Django 3.2.13 on 2022-05-04 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketplace', '0011_auto_20220503_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categorys',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='marketplace.Category'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='categories',
            field=models.ManyToManyField(blank=True, to='marketplace.Category'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(blank=True, to='marketplace.Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
