# Generated by Django 3.2.13 on 2022-05-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20220505_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorys',
            new_name='categories',
        ),
    ]
